version: "2"

services:
  web3ingest.incremental:
    container_name: web3ingest.incremental
    image: web3ingest:5.0.0
    environment:
      - WEB3_PROVIDER=http://52.21.97.126:8545
    volumes:
      - /home/ubuntu/logs:/usr/log
